# Generated by Django 5.0.7 on 2024-07-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements_images/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='announcements_videos/'),
        ),
    ]
